sudo: required

language: node_js

services:
  - docker

node_js:
  - "8"

notifications:
  email:
    - jared.starin@alphapoint.com

before_script:
  - docker build -t nem-node .  

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master